name: Retraction Check
on: [push, pull_request]
jobs:
  check-retractions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: recite/retract@v1.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
