name: Retracted Articles Check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check-retracted-articles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run retraction checker
        uses: recite/retract@v1.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
